"""CONTINUUM — verifiable semantic recovery layer for long-running AI agents.

Agents that can lose their context without losing their work.

Phase 1 exposes the durable data model and the append-only event log. The
runtime (``Continuum``), storage engines, validation, action ledger and CLI
arrive in later phases; nothing here imports an LLM provider.
"""

from continuum.actions import (
    ActionLedger,
    ActionOutcome,
    AssumeNotOccurredReconciler,
    ManualReconciler,
    ProbeReconciler,
    Reconciler,
    ReconciliationReport,
    Resolution,
    arguments_hash,
    idempotency_key,
    reconcile_pending,
    unresolved_actions,
)
from continuum.adapters import (
    AdapterRegistry,
    AgentAdapter,
    GenericAgentAdapter,
    LangChainAgentAdapter,
    LangGraphAgentAdapter,
    OpenAIAgentAdapter,
    get_adapter,
    list_adapters,
    recover,
    register_adapter,
)
from continuum.checkpoint import (
    CheckpointDecision,
    CheckpointError,
    CheckpointManager,
    CheckpointPolicy,
    CheckpointTrigger,
    ContextPressurePolicy,
    EventPolicy,
    HybridPolicy,
    IntervalPolicy,
    ManualPolicy,
    RecoveryContext,
    RestoredRun,
    SemanticPolicy,
    build_recovery_context,
    default_policy,
)
from continuum.environment import (
    CallableProvider,
    EnvironmentDiff,
    EnvironmentProvider,
    FileProvider,
    ResourceChange,
    ResourceDelta,
    StaticProvider,
    ValueProvider,
    capture_environment,
    diff_environments,
)
from continuum.events import (
    AppendOnlyViolation,
    Event,
    EventLog,
    EventType,
    IntegrityReport,
    IntegrityViolation,
)
from continuum.models import (
    Action,
    ActionStatus,
    Approval,
    ApprovalStatus,
    Component,
    ComponentValidationEntry,
    Decision,
    DiffEntry,
    DiffKind,
    EnvironmentSnapshot,
    EnvResource,
    Evidence,
    ExternalDependency,
    Finding,
    Goal,
    ModelSpecificState,
    ModelState,
    Origin,
    PendingWork,
    PlanStep,
    PlanStepStatus,
    Progress,
    Provenance,
    RecoveryContract,
    RecoveryMode,
    RecoverySafety,
    Run,
    RunStatus,
    SemanticState,
    StateCheckpoint,
    StateDiff,
    StateStatus,
    StateValidationResult,
    UnknownSideEffect,
    utcnow,
)
from continuum.provenance_map import (
    CanonicalProvenance,
    ProvenanceView,
    canonical_origin,
    canonical_state_status,
    canonical_trust,
    summarize,
)
from continuum.recovery import (
    DependencyGraph,
    ImpactedSet,
    LedgerEntryKind,
    ReconcileReport,
    RecoveryDecision,
    RecoveryEngine,
    RecoveryLedger,
    RecoveryLedgerEntry,
    RepairKind,
    RepairPlan,
    RepairStep,
    build_contract,
    plan_repairs,
    render_contract,
    verify_contract,
)
from continuum.state import (
    CompositeExtractor,
    DeterministicExtractor,
    ExtractionContext,
    LLMExtractor,
    LLMProposal,
    ProjectionError,
    StateExtractor,
    VersionChain,
    VersionEntry,
    diff_states,
    project,
    project_incremental,
    render_diff,
    state_fingerprint,
)
from continuum.state.validator import StateValidator, ValidationOutcome, validate_state
from continuum.storage import (
    CheckpointNotFound,
    ConcurrentWriteError,
    CorruptedRecord,
    RunNotFound,
    SchemaVersionError,
    SQLiteStorage,
    Storage,
    StorageError,
    open_storage,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    # events
    "AppendOnlyViolation",
    "Event",
    "EventLog",
    "EventType",
    "IntegrityReport",
    "IntegrityViolation",
    # enums
    "ActionStatus",
    "ApprovalStatus",
    "Component",
    "DiffKind",
    "Origin",
    "PlanStepStatus",
    "RecoveryMode",
    "RecoverySafety",
    "RunStatus",
    "StateStatus",
    # state
    "Action",
    "Approval",
    "ComponentValidationEntry",
    "Decision",
    "DiffEntry",
    "EnvResource",
    "EnvironmentSnapshot",
    "Evidence",
    "ExternalDependency",
    "Finding",
    "Goal",
    "ModelSpecificState",
    "ModelState",
    "PendingWork",
    "PlanStep",
    "Progress",
    "Provenance",
    "Run",
    "RecoveryContract",
    "SemanticState",
    "StateCheckpoint",
    "StateDiff",
    "StateValidationResult",
    "UnknownSideEffect",
    "utcnow",
    # projection, extraction, versioning, diffing
    "CompositeExtractor",
    "DeterministicExtractor",
    "ExtractionContext",
    "LLMExtractor",
    "LLMProposal",
    "ProjectionError",
    "StateExtractor",
    "VersionChain",
    "VersionEntry",
    "diff_states",
    "project",
    "project_incremental",
    "render_diff",
    "state_fingerprint",
    # storage
    "CheckpointNotFound",
    "ConcurrentWriteError",
    "CorruptedRecord",
    "RunNotFound",
    "SQLiteStorage",
    "SchemaVersionError",
    "Storage",
    "StorageError",
    "open_storage",
    # checkpointing
    "CheckpointDecision",
    "CheckpointError",
    "CheckpointManager",
    "CheckpointPolicy",
    "CheckpointTrigger",
    "ContextPressurePolicy",
    "EventPolicy",
    "HybridPolicy",
    "IntervalPolicy",
    "ManualPolicy",
    "RecoveryContext",
    "RestoredRun",
    "SemanticPolicy",
    "build_recovery_context",
    "default_policy",
    # environment + validation
    "CallableProvider",
    "EnvironmentDiff",
    "EnvironmentProvider",
    "FileProvider",
    "ResourceChange",
    "ResourceDelta",
    "StateValidator",
    "StaticProvider",
    "ValidationOutcome",
    "ValueProvider",
    "capture_environment",
    "diff_environments",
    "validate_state",
    # action ledger
    "ActionLedger",
    "ActionOutcome",
    "AssumeNotOccurredReconciler",
    "ManualReconciler",
    "ProbeReconciler",
    "Reconciler",
    "ReconciliationReport",
    "Resolution",
    "arguments_hash",
    "idempotency_key",
    "reconcile_pending",
    "unresolved_actions",
    # recovery engine
    "DependencyGraph",
    "ImpactedSet",
    "LedgerEntryKind",
    "RecoveryDecision",
    "RecoveryEngine",
    "RecoveryLedger",
    "RecoveryLedgerEntry",
    "ReconcileReport",
    "RepairKind",
    "RepairPlan",
    "RepairStep",
    "build_contract",
    "plan_repairs",
    "render_contract",
    "verify_contract",
    # agent framework adapters
    "AdapterRegistry",
    "AgentAdapter",
    "GenericAgentAdapter",
    "LangChainAgentAdapter",
    "LangGraphAgentAdapter",
    "OpenAIAgentAdapter",
    "get_adapter",
    "list_adapters",
    "recover",
    "register_adapter",
    # provenance (canonical mapping)
    "CanonicalProvenance",
    "ProvenanceView",
    "canonical_origin",
    "canonical_state_status",
    "canonical_trust",
    "summarize",
]
